import pygame


#CONSTANTS
SCREEN_WIDTH = 1800
SCREEN_HEIGHT = 1000
screen = pygame.display.set_mode([SCREEN_WIDTH, SCREEN_HEIGHT])

#ALIENT CONTANTS
ALIEN_AMOUNT_ROW = 1
ALIEN_AMOUNT_COLUMN = 1
X_OFFSET = 30
Y_OFFSET = 100
WIDTH = 30

#PLAYER CONSTANTS
PLAYERCOLOR = (255,255,0)

#COLORS
CLEAR = (0,0,0)
